version: "3.9"
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
    volumes:
#      - .:/var/jenkins_home
      - .:/code
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: password
# docker build -t jenkins:jcasc .
# docker run --name jenkins --rm -p 8080:8080 --env JENKINS_ADMIN_ID=admin --env JENKINS_ADMIN_PASSWORD=password jenkins:jcasc
